[package]
name = "lithium"
version = "0.1.0"
edition = "2021"

[lib]
name = "kernel"
path = "kernel/lib.rs"
crate-type = ["staticlib", "lib"]

[dependencies]
bitflags = "2.4.1"
raw-cpuid = "11.0.1"
x86_64 = "0.14.11"
