[package]
name = "lithium"
version = "0.1.0"
edition = "2021"

[lib]
name = "lithium"
path = "kernel/lib.rs"
crate-type = ["staticlib", "lib"]

[dependencies]
bit_field = "0.10.2"
bitflags = "2.4.1"
linked_list_allocator = "0.10.5"
raw-cpuid = "11.0.1"
spin = "0.9.8"
x86_64 = "0.14.11"
